server:
  port: 8081
spring:
  profiles:
    include:
      common
onework:
  translate:
    baidu:
      url: https://fanyi-api.baidu.com/api/trans/vip/translate
      appId: 20210206000692404
      secretKey: 26ZZ7HwrFuxiOcAQ_inQ
