spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/onework-test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
  sql:
    init:
      schema-locations: classpath:db/schema-onework.sql
      data-locations: classpath:db/data-onework.sql
      mode: always
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl