spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-onework.sql
    data: classpath:db/data-onework.sql
    url: mysql://127.0.0.1:3306/onework-text?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
