spring:
  datasource:
    username: root
    password: 123qwe!@#mysql_root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://101.37.81.183:8033/onework?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
  mvc:
    static-path-pattern: /static/**
    log-request-details: true
    log-resolved-exception: true
  devtools:
    restart:
      enabled: true
      additional-exclude: templates/**
      additional-paths: src/main/java
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_at
      logic-not-delete-value: "null"
      id-type: ASSIGN_ID
      logic-delete-value: now()
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8081
  servlet:
    context-path: /api
springdoc:
  version: '1.0.0 base'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
logging:
  level:
    com:
      onework:
        tools: debug